version: '3'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - php

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    networks:
      - php
    depends_on:
      - php
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: posts
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    networks:
      - php
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql

networks:
  php:
